<a href="https://colab.research.google.com/github/ankritRisal/Finetuning_LLM/blob/main/Book_Dataset_EDA_and_Systemprompt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv("/content/drive/MyDrive/X3s4c5/FinetunningLLMmodels/archive/Book_Dataset_1.csv")
df.head(5)

Unnamed: 0                                  Title            Category  \
0           0                   A Light in the Attic              Poetry   
1           1                     Tipping the Velvet  Historical Fiction   
2           2                             Soumission             Fiction   
3           3                          Sharp Objects             Mystery   
4           4  Sapiens: A Brief History of Humankind             History   

   Price  Price_After_Tax  Tax_amount  Avilability  Number_of_reviews  \
0  51.77            51.77         0.0           22                  0   
1  53.74            53.74         0.0           20                  0   
2  50.10            50.10         0.0           20                  0   
3  47.82            47.82         0.0           20                  0   
4  54.23            54.23         0.0           20                  0   

                                    Book_Description  \
0  It's hard to imagine a world without A Light i...   
1  "Erotic and absorbing...Written with starling ...   
2  Dans une France assez proche de la nôtre, un ...   
3  WICKED above her hipbone, GIRL across her hear...   
4  From a renowned historian comes a groundbreaki...   

                                          Image_Link  Stars  
0  http://books.toscrape.com/media/cache/fe/72/fe...      3  
1  http://books.toscrape.com/media/cache/08/e9/08...      1  
2  http://books.toscrape.com/media/cache/ee/cf/ee...      1  
3  http://books.toscrape.com/media/cache/c0/59/c0...      4  
4  http://books.toscrape.com/media/cache/ce/5f/ce...      5

In [4]:
df.drop(["Image_Link", "Number_of_reviews", "Tax_amount", "Price_After_Tax"], axis = 1, inplace = True)

In [5]:
df.head(5)

Unnamed: 0                                  Title            Category  \
0           0                   A Light in the Attic              Poetry   
1           1                     Tipping the Velvet  Historical Fiction   
2           2                             Soumission             Fiction   
3           3                          Sharp Objects             Mystery   
4           4  Sapiens: A Brief History of Humankind             History   

   Price  Avilability                                   Book_Description  \
0  51.77           22  It's hard to imagine a world without A Light i...   
1  53.74           20  "Erotic and absorbing...Written with starling ...   
2  50.10           20  Dans une France assez proche de la nôtre, un ...   
3  47.82           20  WICKED above her hipbone, GIRL across her hear...   
4  54.23           20  From a renowned historian comes a groundbreaki...   

   Stars  
0      3  
1      1  
2      1  
3      4  
4      5

In [ ]:
df.to_csv("/content/drive/MyDrive/X3s4c5/FinetunningLLMmodels/book_description.csv")

#loading new DF[link text](https://)

In [ ]:
new_df = pd.read_csv("/content/drive/MyDrive/X3s4c5/FinetunningLLMmodels/book_description.csv")

In [ ]:
new_df.head(10)

Unnamed: 0.1  Unnamed: 0  \
0             0           0   
1             1           1   
2             2           2   
3             3           3   
4             4           4   
5             5           5   
6             6           6   
7             7           7   
8             8           8   
9             9           9   

                                               Title            Category  \
0                               A Light in the Attic              Poetry   
1                                 Tipping the Velvet  Historical Fiction   
2                                         Soumission             Fiction   
3                                      Sharp Objects             Mystery   
4              Sapiens: A Brief History of Humankind             History   
5                                    The Requiem Red         Young Adult   
6  The Dirty Little Secrets of Getting Your Dream...            Business   
7  The Coming Woman: A Novel Based on the Life of...             Default   
8  The Boys in the Boat: Nine Americans and Their...             Default   
9                                    The Black Maria              Poetry   

   Price  Avilability                                   Book_Description  \
0  51.77           22  It's hard to imagine a world without A Light i...   
1  53.74           20  "Erotic and absorbing...Written with starling ...   
2  50.10           20  Dans une France assez proche de la nôtre, un ...   
3  47.82           20  WICKED above her hipbone, GIRL across her hear...   
4  54.23           20  From a renowned historian comes a groundbreaki...   
5  22.65           19  Patient Twenty-nine.A monster roams the halls ...   
6  33.34           19  Drawing on his extensive experience evaluating...   
7  17.93           19  "If you have a heart, if you have a soul, Kare...   
8  22.60           19  For readers of Laura Hillenbrand's Seabiscuit ...   
9  52.15           19  Praise for Aracelis Girmay:"[Girmay's] every l...   

   Stars  
0      3  
1      1  
2      1  
3      4  
4      5  
5      1  
6      4  
7      3  
8      4  
9      1

In [ ]:
new_df["Book_Description"][0]

"It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounde

In [ ]:
cat = new_df['Category'].unique()
cat[0]

'Poetry'

In [ ]:
list(cat)

['Poetry',
 'Historical Fiction',
 'Fiction',
 'Mystery',
 'History',
 'Young Adult',
 'Business',
 'Default',
 'Sequential Art',
 'Music',
 'Science Fiction',
 'Politics',
 'Travel',
 'Thriller',
 'Food and Drink',
 'Romance',
 'Childrens',
 'Nonfiction',
 'Art',
 'Spirituality',
 'Philosophy',
 'New Adult',
 'Contemporary',
 'Fantasy',
 'Add a comment',
 'Science',
 'Health',
 'Horror',
 'Self Help',
 'Religion',
 'Christian',
 'Crime',
 'Autobiography',
 'Christian Fiction',
 'Biography',
 'Womens Fiction',
 'Erotica',
 'Cultural',
 'Psychology',
 'Humor',
 'Historical',
 'Novels',
 'Short Stories',
 'Suspense',
 'Classics',
 'Academic',
 'Sports and Games',
 'Adult Fiction',
 'Parenting',
 'Paranormal']

In [ ]:
new_df.count()

Unnamed: 0.1        1000
Unnamed: 0          1000
Title               1000
Category            1000
Price               1000
Avilability         1000
Book_Description    1000
Stars               1000
dtype: int64

# ingest for finetunning LLM models

In [7]:
valid_category  = list(df['Category'].unique())

In [9]:
system_prompt = {
    "role" : "system",
    "content" : f""" You are an AI system that reads an Title and Book Description and classifies category of the book applied, you must
    choose from the following classes:
    {"\n or ". join(["Labeled Category:" + x for x in list(valid_category)])}.
    Ensure Output is from above list only"""
    }

post_messages = \
    {
        "role" : "assistant",
        "content" : "Labeled Category"
    }

user_messages = \
    {
      "role" : "user",
      "content" : """ Title :A Light in the Attic
                    Book Description: It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby,
                    I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"""
    }

In [10]:
prompt = [
    [system_prompt, user_messages, post_messages]
]

# inititate Model

In [12]:
import numpy as np
import pandas as pd

In [13]:
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

In [14]:
from google.colab import userdata
from huggingface_hub import login

# Get the token from Colab secrets
hf_token = userdata.get('HF_TOKEN')

login(token=hf_token)

In [15]:
# model_id = "meta-llama/Llama-3.2-3B-Instruct"
model_id = "meta-llama/Llama-3.2-1B-Instruct"

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side ="left")
tokenizer.pad_token = tokenizer.eos_token # padding tokens to make of same shape

model = AutoModelForCausalLM.from_pretrained(model_id,
                                             dtype = torch.bfloat16,
                                             device_map = device)

config.json:   0%|          | 0.00/877 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [16]:
device

'cuda'

# Visualizing training Workflow in dataset and PEFT model

In [18]:
tokenizer.pad_token = tokenizer.eos_token # padding tokens to make of same shape
tokenized = tokenizer.apply_chat_template(prompt,
                              continue_final_message = True,
                              # tokenize = True,
                              padding = True,
                              return_tensors = "pt").to(device)

In [21]:
target_response = ["Default"]

In [26]:
def generate_input_output_pair(prompt, target_responses):
  chat_templates = tokenizer.apply_chat_template(prompt, continue_final_message= True, tokenize= False)
  # print(chat_templates)
  full_response_text = [
      (chat_template + " " + target_response + tokenizer.eos_token)
      for chat_template, target_response in zip(chat_templates, target_responses)
      ]
  # print(full_response_text)

  input_ids_tokenized = tokenizer(full_response_text, add_special_tokens = False, return_tensors ="pt")["input_ids"]
  label_tokenized = tokenizer([" " + response + tokenizer.eos_token for response in target_responses], add_special_tokens = False,
                              return_tensors ="pt", padding = "max_length", max_length = input_ids_tokenized.shape[1])["input_ids"]

  label_tokenized_fixed = torch.where(label_tokenized != tokenizer.pad_token_id, label_tokenized, -100)
  label_tokenized_fixed[:, -1] = tokenizer.eos_token_id

  input_ids_tokenized_left_shifted = input_ids_tokenized[:, :-1]
  label_tokenized_right_shifted = label_tokenized_fixed[:, 1:]

  attention_mask = input_ids_tokenized_left_shifted != tokenizer.pad_token_id
  return {
      "input_ids" : input_ids_tokenized_left_shifted,
      "attention_mask" : attention_mask,
      "labels" : label_tokenized_right_shifted
  }


In [27]:
import torch.nn as nn
from torch.optim import AdamW

def calculate_loss(logits, labels):
  loss_fn = nn.CrossEntropyLoss()
  entropyloss = loss_fn(logits.view(-1, logits.size(-1)), labels.reshape(-1))
  return entropyloss

In [28]:
# LORA ADAPTOR
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    task_type = "CAUSAL_LM",
    r = 4,
    lora_alpha = 16,
    lora_dropout = 0.05,
    target_modules = ['q_proj', 'v_proj']
)

peft_model = get_peft_model(model, lora_config)
peft_model.print_trainable_parameters()

trainable params: 425,984 || all params: 1,236,240,384 || trainable%: 0.0345


/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(


In [31]:
target_response

['Default']

In [32]:
data = generate_input_output_pair(prompt = prompt, target_responses= target_response)

In [34]:
data["input_ids"].shape

torch.Size([1, 718])

In [35]:
data["labels"].shape

torch.Size([1, 718])

In [36]:
out = model(input_ids = data["input_ids"].to(device))

In [37]:
out.logits.shape

torch.Size([1, 718, 128256])

In [39]:
loss = calculate_loss(out.logits, data["labels"].to(device))

In [40]:
loss

tensor(11.6250, device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<NllLossBackward0>)

In [43]:
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr = 1e-3, weight_decay= 0.01)

for i in range(10):
  out = peft_model(input_ids = data["input_ids"].to(device))
  print(out.logits.shape)
  loss = calculate_loss(out.logits, data["labels"].to(device)).mean()

  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

  print(f"loss : {loss.item()}")

torch.Size([1, 718, 128256])
loss : 0.00555419921875
torch.Size([1, 718, 128256])
loss : 0.01043701171875
torch.Size([1, 718, 128256])
loss : 0.00051116943359375
torch.Size([1, 718, 128256])
loss : 0.000507354736328125
torch.Size([1, 718, 128256])
loss : 0.0003757476806640625
torch.Size([1, 718, 128256])
loss : 0.00023651123046875
torch.Size([1, 718, 128256])
loss : 0.0001735687255859375
torch.Size([1, 718, 128256])
loss : 0.00012874603271484375
torch.Size([1, 718, 128256])
loss : 0.000102996826171875
torch.Size([1, 718, 128256])
loss : 8.869171142578125e-05


# Test prompt

[[{'role': 'system',
   'content': ' You are an AI system that reads an Title and Book Description and classifies category of the book applied, you must\n    choose from the following classes:\n    Labeled Category:Poetry\n or Labeled Category:Historical Fiction\n or Labeled Category:Fiction\n or Labeled Category:Mystery\n or Labeled Category:History\n or Labeled Category:Young Adult\n or Labeled Category:Business\n or Labeled Category:Default\n or Labeled Category:Sequential Art\n or Labeled Category:Music\n or Labeled Category:Science Fiction\n or Labeled Category:Politics\n or Labeled Category:Travel\n or Labeled Category:Thriller\n or Labeled Category:Food and Drink\n or Labeled Category:Romance\n or Labeled Category:Childrens\n or Labeled Category:Nonfiction\n or Labeled Category:Art\n or Labeled Category:Spirituality\n or Labeled Category:Philosophy\n or Labeled Category:New Adult\n or Labeled Category:Contemporary\n or Labeled Category:Fantasy\n or Labeled Category:Add a comment

In [46]:
# test_tokenized = tokenizer.apply_chat_template(prompt, continue_final_message= True, return_tensors ="pt").to(device)
# test_out = peft_model.generate(test_tokenized, max_new_tokens = 10)
# print(tokenizer.batch_decode(test_out, skip_special_tokens= True)[0])

In [48]:
def extract_labels_from_output(decode_batch, tokenizer):
  labels = []
  for d in decode_batch:
    # print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
    # print(d)
    label = d.split("Labeled Category :")[1].strip()
    # print(label)
    labels.append(label)
  # labels = [d.split("<|start_header_id|>assistant<|end_header_id|>\n\nLabeled Category:")[0].split("<|eot_id|>")[0].strip() for d in decode_batch]
  # print(labels)
  # labels  = [d.split("<|start_header_id|>assistant<|end_header_id|>\n\nLabeled Category:")[1].split("<|eot_id|>")[0].strip() for d in decode_batch]
  return labels

In [56]:
tokenizer.pad_token = tokenizer.eos_token
# tokenized = tokenizer(prompt, padding= True, return_tensors ="pt", add_special_tokens= False).to(device)
tokenized = tokenizer.apply_chat_template(prompt, padding= False, return_tensors ="pt", add_special_tokens= False).to(device)
output_batch = peft_model.generate(input_ids = tokenized["input_ids"], attention_mask =tokenized["attention_mask"], max_new_tokens = 20, do_sample= False, temperature = 0, top_p =1)
# output_batch = model.generate(tokenized, max_new_tokens = 20)
decode_batch = tokenizer.batch_decode(output_batch, skip_special_tokens= True)



Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


In [57]:
decode_batch # Obtained decode

["system\n\nCutting Knowledge Date: December 2023\nToday Date: 12 Feb 2026\n\nYou are an AI system that reads an Title and Book Description and classifies category of the book applied, you must\n    choose from the following classes:\n    Labeled Category:Poetry\n or Labeled Category:Historical Fiction\n or Labeled Category:Fiction\n or Labeled Category:Mystery\n or Labeled Category:History\n or Labeled Category:Young Adult\n or Labeled Category:Business\n or Labeled Category:Default\n or Labeled Category:Sequential Art\n or Labeled Category:Music\n or Labeled Category:Science Fiction\n or Labeled Category:Politics\n or Labeled Category:Travel\n or Labeled Category:Thriller\n or Labeled Category:Food and Drink\n or Labeled Category:Romance\n or Labeled Category:Childrens\n or Labeled Category:Nonfiction\n or Labeled Category:Art\n or Labeled Category:Spirituality\n or Labeled Category:Philosophy\n or Labeled Category:New Adult\n or Labeled Category:Contemporary\n or Labeled Category:Fa

# Visualization of prompt terms such as attention_mask, input_ids

In [ ]:
tokenized = tokenizer(prompt,
                              # continue_final_message = True,
                              # tokenize = True,
                              padding = True,
                              return_tensors = "pt").to(device)

In [ ]:
tokenized["attention_mask"]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1

In [ ]:
next(model.parameters()).device


device(type='cuda', index=0)

In [ ]:
out = model.generate(tokenized, max_new_tokens = 20)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [ ]:
decode = tokenizer.batch_decode(out)

In [ ]:
decode

["<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 23 Jan 2026\n\nYou are an AI system that reads an Title and Book Description and classifies category of the book applied, you must\n    choose from the following classes:\n    Labeled Category:Poetry\n or Labeled Category:Historical Fiction\n or Labeled Category:Fiction\n or Labeled Category:Mystery\n or Labeled Category:History\n or Labeled Category:Young Adult\n or Labeled Category:Business\n or Labeled Category:Default\n or Labeled Category:Sequential Art\n or Labeled Category:Music\n or Labeled Category:Science Fiction\n or Labeled Category:Politics\n or Labeled Category:Travel\n or Labeled Category:Thriller\n or Labeled Category:Food and Drink\n or Labeled Category:Romance\n or Labeled Category:Childrens\n or Labeled Category:Nonfiction\n or Labeled Category:Art\n or Labeled Category:Spirituality\n or Labeled Category:Philosophy\n or Labeled Category:New Adult\n or L

In [ ]:
labels  = [d.split("<|start_header_id|>assistant<|end_header_id|>\n\nLabeled Category:")[1].split("<|eot_id|>")[0].strip() for d in decode]

In [ ]:
labels

['Poetry']

# Understanding the Loss function and next word prediction

In [ ]:
device

'cuda'

In [ ]:
sentence = ["Subscribe to my channel"]
tokenized = tokenizer(sentence, return_tensors="pt")["input_ids"]
print(tokenized)

tensor([[128000,  29673,    311,    856,   5613]])


In [ ]:
print(tokenizer.batch_decode(tokenized))

['<|begin_of_text|>Subscribe to my channel']


In [ ]:
input_ids = tokenized[:, :-1]
target_ids = tokenized[:, 1:]
print(input_ids, target_ids)

tensor([[128000,  29673,    311,    856]]) tensor([[29673,   311,   856,  5613]])


In [ ]:
question = "Capital of Nepal"
answer = "Kathmandu"

prompt = [
    {"role" : "user", "content" : "Capital of Nepal?"},
    {"role" : "assistant", "content" : "Capital:"}
]

chat_template = tokenizer.apply_chat_template(prompt, continue_final_message= True, tokenize= False)
print(chat_template)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2026

<|eot_id|><|start_header_id|>user<|end_header_id|>

Capital of Nepal?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Capital:


In [ ]:
full_response = chat_template + " " + answer + tokenizer.eos_token
print(full_response)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2026

<|eot_id|><|start_header_id|>user<|end_header_id|>

Capital of Nepal?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Capital: Kathmandu<|eot_id|>


In [ ]:
tokenized = tokenizer(full_response, return_tensors = "pt", add_special_tokens= False)["input_ids"]
print(tokenized)

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   2437,  13806,    220,   2366,     21,    271, 128009, 128006,
            882, 128007,    271,  64693,    315,  50064,     30, 128009, 128006,
          78191, 128007,    271,  64693,     25,  33995,   1969,     84, 128009]])


In [ ]:
input_ids = tokenized[:, :-1]
target_ids = tokenized[:, 1:]
print(input_ids, target_ids)

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   2437,  13806,    220,   2366,     21,    271, 128009, 128006,
            882, 128007,    271,  64693,    315,  50064,     30, 128009, 128006,
          78191, 128007,    271,  64693,     25,  33995,   1969,     84]]) tensor([[128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,     25,
           6790,    220,   2366,     18,    198,  15724,   2696,     25,    220,
           2437,  13806,    220,   2366,     21,    271, 128009, 128006,    882,
         128007,    271,  64693,    315,  50064,     30, 128009, 128006,  78191,
         128007,    271,  64693,     25,  33995,   1969,     84, 128009]])


In [ ]:
print(tokenizer.convert_ids_to_tokens(33995))
print(tokenizer.convert_ids_to_tokens(1969))
print(tokenizer.convert_ids_to_tokens(84))

ĠKath
mand
u


In [ ]:
label_tokenized = tokenizer([" " + answer], add_special_tokens = False, return_tensors ="pt")["input_ids"]
label_tokenized

tensor([[33995,  1969,    84]])

In [ ]:
input_ids.shape[1]


44

In [ ]:
label_tokenized = tokenizer([" " + answer + tokenizer.eos_token], add_special_tokens = False, return_tensors ="pt", padding = "max_length", max_length = input_ids.shape[1])["input_ids"]
label_tokenized

tensor([[128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009, 128009,
         128009, 128009, 128009, 128009,  33995,   1969,     84, 128009]])

In [ ]:
label_tokenized_fixed = torch.where(label_tokenized != tokenizer.pad_token_id, label_tokenized, -100)
label_tokenized_fixed

tensor([[ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         33995,  1969,    84,  -100]])

In [ ]:
label_tokenized_fixed[:, -1] = tokenizer.eos_token_id
label_tokenized_fixed

tensor([[  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,  33995,   1969,     84, 128009]])

In [ ]:
def generate_input_output_pair(prompt, target_responses):
  chat_templates = tokenizer.apply_chat_template(prompt, continue_final_message= True, tokenize= False)
  # print(chat_templates)
  full_response_text = [
      (chat_template + " " + target_response + tokenizer.eos_token)
      for chat_template, target_response in zip(chat_templates, target_responses)
      ]
  # print(full_response_text)

  input_ids_tokenized = tokenizer(full_response_text, add_special_tokens = False, return_tensors ="pt")["input_ids"]
  label_tokenized = tokenizer([" " + response + tokenizer.eos_token for response in target_responses], add_special_tokens = False,
                              return_tensors ="pt", padding = "max_length", max_length = input_ids_tokenized.shape[1])["input_ids"]

  label_tokenized_fixed = torch.where(label_tokenized != tokenizer.pad_token_id, label_tokenized, -100)
  label_tokenized_fixed[:, -1] = tokenizer.eos_token_id

  input_ids_tokenized_left_shifted = input_ids_tokenized[:, :-1]
  label_tokenized_right_shifted = label_tokenized_fixed[:, 1:]

  attention_mask = input_ids_tokenized_left_shifted != tokenizer.pad_token_id
  return {
      "input_ids" : input_ids_tokenized_left_shifted,
      "attention_mask" : attention_mask,
      "labels" : label_tokenized_right_shifted
  }


In [ ]:
prompt = [
    {"role" : "user", "content" : "Capital of Nepal?"},
    {"role" : "assistant", "content" : "Capital:"}
],
target_responses = ["Kathmandu"]


In [ ]:
data = generate_input_output_pair(prompt, target_responses)

In [ ]:
data["input_ids"]

tensor([[128000, 128006,   9125, 128007,    271,  38766,   1303,  33025,   2696,
             25,   6790,    220,   2366,     18,    198,  15724,   2696,     25,
            220,   2437,  13806,    220,   2366,     21,    271, 128009, 128006,
            882, 128007,    271,  64693,    315,  50064,     30, 128009, 128006,
          78191, 128007,    271,  64693,     25,  33995,   1969,     84]])

In [ ]:
data["labels"].shape

torch.Size([1, 44])

In [ ]:
out = model(input_ids = data["input_ids"].to(device))

In [ ]:
out.logits.shape

torch.Size([1, 44, 128256])

In [ ]:
out.logits.view(-1, out.logits.size(-1)).shape

torch.Size([44, 128256])

In [ ]:
data["labels"].view(-1).shape

torch.Size([44])

In [ ]:
import torch.nn as nn

def calculate_loss(logits, labels):
  loss_fn = nn.CrossEntropyLoss(reduction= 'none')
  entropyloss = loss_fn(logits.view(-1, logits.size(-1)), labels.view(-1))
  return entropyloss

In [ ]:
loss = calculate_loss(out.logits, data["labels"].to(device))

In [ ]:
loss

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5430e-01, 5.4359e-05,
        2.7061e-05, 8.4473e-02], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<NllLossBackward0>)

In [ ]:
out.logits.argmax(-1)

tensor([[   791, 128006,    198,    271,    334,   1303,  48448,    520,     25,
           6186,    220,   2366,     17,    198,  32176,    596,     25,    220,
           1591,   3297,    220,   2366,     19,    198,    334,    475,  78191,
         128007,    271,    334,   4954,  48847,    198, 128009, 128006,  78191,
         128007,    271,     42,    315,  33995,   1969,     84, 128009]],
       device='cuda:0')

# PEFT: LORA Adaptor

In [ ]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    task_type = "CAUSAL_LM",
    r = 64,
    lora_alpha = 16,
    lora_dropout = 0.1,
    target_modules = ['q_proj', 'v_proj']
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 6,815,744 || all params: 1,242,630,144 || trainable%: 0.5485


# Training loop

In [ ]:
training_prompt = [
    {
        "role" : "user", "content" : "Who to subscribe for travel videos?"
    },
    {
        "role" : "assistant", "content" : "Subscribe to"
    }
]
target_response = ["TravelWithRam"]

In [ ]:
data = generate_input_output_pair(prompt= [training_prompt], target_responses= target_response)

In [ ]:
data["input_ids"] = data["input_ids"].to(device)

In [ ]:
data["input_ids"].shape

torch.Size([1, 47])

In [ ]:
out = model(input_ids = data["input_ids"].to(device))

In [ ]:
out.logits.view(-1, out.logits.size(-1)).shape

torch.Size([47, 128256])

In [ ]:
data["labels"] = data["labels"].to(device)

In [ ]:
data["labels"].view(-1).shape

torch.Size([47])

In [ ]:
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr = 1e-3, weight_decay= 0.01)

for i in range(10):
  out = model(input_ids = data["input_ids"].to(device))
  print(out.logits.shape)
  loss = calculate_loss(out.logits, data["labels"]).mean()

  loss.backward()
  optimizer.step()
  optimizer.zero_grad()

  print(f"loss : {loss.item()}")

torch.Size([1, 47, 128256])
loss : 0.47265625
torch.Size([1, 47, 128256])
loss : 0.2099609375
torch.Size([1, 47, 128256])
loss : 0.09228515625
torch.Size([1, 47, 128256])
loss : 0.01226806640625
torch.Size([1, 47, 128256])
loss : 0.0004062652587890625
torch.Size([1, 47, 128256])
loss : 0.000247955322265625
torch.Size([1, 47, 128256])
loss : 0.0003662109375
torch.Size([1, 47, 128256])
loss : 0.00043487548828125
torch.Size([1, 47, 128256])
loss : 0.000431060791015625
torch.Size([1, 47, 128256])
loss : 0.0004024505615234375


In [ ]:
test_tokenized = tokenizer.apply_chat_template(training_prompt, continue_final_message= True, return_tensors ="pt").to(device)
test_out = model.generate(test_tokenized, max_new_tokens = 10)
print(tokenizer.batch_decode(test_out, skip_special_tokens= True)[0])

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


system

Cutting Knowledge Date: December 2023
Today Date: 02 Feb 2026

user

Who to subscribe for travel videos?assistant

Subscribe to TravelWithRam
